# Generated by Django 5.1.6 on 2025-03-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('period', models.CharField(choices=[('01 Petit Déjeuner', 'Petit Déjeuner'), ('02 Collation AM', 'Collation AM'), ('03 Déjeuner', 'Déjeuner'), ('04 Collation PM', 'Collation PM'), ('05 Dîner', 'Dîner'), ('06 Activité Physique', 'Activité Physique'), ('07 Hydratation', 'Hydratation')], max_length=20)),
                ('activity', models.CharField(choices=[('Nourriture', 'Nourriture'), ('Complément', 'Complément'), ('None', 'Aucune')], max_length=20)),
                ('data', models.CharField(max_length=255)),
                ('kcal', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
            },
        ),
    ]
